// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int number = Integer.parseInt(args[0]);
		double num = Math.random();
		int countless=0;
		int countabove=0;
		for(int i=0;i<number;i++)
		{
		   num = Math.random();
			if(num>0.5)
			{
				countabove++;
			}
			if(num<=0.5)
			{
				countless++;
			}
			
		}
		
		System.out.println("above 0.5 "+countabove);
		System.out.println("less 0.5 "+countless);
		if(countless!=0)
		{
		   double ratio=(double)countabove/countless;
		   System.out.println("the ratio is "+ratio);
		}
	}
}
